### ISSUE TITLE
Does it support lua script?

### ISSUE THREAD

**Issue by johnlau3** [mna/redisc#16]
Does it support lua script?

**Comment by mna** [comment]
Yes, within the limits inherent to Redis Cluster (all keys used by the script must live on the same node). I should add an example of how to use scripting with redisc, but you can take a look at the tests in the meantime: 
https://github.com/mna/redisc/blob/master/cluster_test.go

**Comment by mna** [comment]
There's an example here, will close this: https://pkg.go.dev/github.com/mna/redisc#example-Conn.
