### ISSUE TITLE
Feature request: Support ConnWithTimeouts

### ISSUE THREAD

**Issue by jandre-r7** [mna/redisc#17]
Update internal Conn structure needs to support

https://github.com/gomodule/redigo/blob/bb5990dc771ab24e169aaea90ee3b9ad50cffce9/redis/redis.go#L82

**Comment by mna** [comment]
Interesting, thanks for the heads-up. Can't promise anything soon, if anyone wants to submit a PR for this (with tests), I'll be happy to review and help landing it.
