### ISSUE TITLE
The slot is UNWRITEABLE when migrate slot

### ISSUE THREAD

**Issue by yuelng** [mna/redisc#18]
When migrate slot，the cluster return ‘ASK’ err，but I found the client not process this situation correctly， help wanted， thanks  @mna

**Comment by yuelng** [comment]
```go
	// forceDial doesn't require locking (immutable)
		conn, addr, err := cluster.getConnForSlot(re.NewSlot, rc.c.forceDial, readOnly)
		if err != nil {
			// could not get connection to that node, return that error
			return nil, err
		}
```
https://github.com/mna/redisc/blob/master/retry_conn.go#L86
should replace by?
```go
conn, err := cluster.getConnForAddr(re.Addr, rc.c.forceDial)
```

**Comment by mna** [comment]
Please clarify the issue, at a minimum it should clearly state (with minimal code to reproduce):

* What you did (call method X with struct Y)
* What happened (describe the exact error, any relevant output, etc.)
* What you expected to happen

From what I understand of your issue, you should make sure you're using a `RetryConn` if you want to automatically follow the `ASK` responses, see https://godoc.org/github.com/mna/redisc#hdr-Redirections.

**Comment by yuelng** [comment]
thanks your response，absolutely，I am using a `RetryConn`，I found When migrate slot，the cluster return ‘ASK’ err，the client should take the redirection addr returned by err response，but from the client logic
```go
conn, addr, err := cluster.getConnForSlot(re.NewSlot, rc.c.forceDial, readOnly)
if err != nil {
	// could not get connection to that node, return that error
	return nil, err
}
```
you still take the address from the cache mapping，this is work for `MOVED` err response, but the retry logic take the wrong address repeatedly，So I suggest that you replace the above code，with this
```go
conn, err := cluster.getConnForAddr(re.Addr, rc.c.forceDial)
```
for example：the slot 8903 is mapping the node 10.1.171.237:7008, when migrate slot 8903 to node  10.1.171.238，we have operate on this slot， then the client will got err  `(error) ASK 8903 10.1.171.238:7008`,  so the client should connect the node 10.1.171.238，not 10.1.171.237。but from the source code，you still use the mapping relation slot-address 8903 - 10.1.171.237。
