### ISSUE TITLE
add password 

### ISSUE THREAD

**Issue by 1768626816** [mna/redisc#21]
need password to auth

**Comment by mna** [comment]
Hello,

You set the password using redigo's `DialPassword` function that creates a `DialOption` (https://godoc.org/github.com/gomodule/redigo/redis#DialPassword). You add this in the list of `DialOption`s on the `redisc.Cluster.DialOptions` field (https://godoc.org/github.com/mna/redisc#Cluster).

Hope this helps,
Martin

**Comment by 1768626816** [comment]
thanks，it work。
