### ISSUE TITLE
Connection failes if cluster consists only from one master

### ISSUE THREAD

**Issue by lohmag** [mna/redisc#33]
If redis cluster consists only from one master node, this lib doesn't works. If there is >1 master node it works fine.
```
{"level":"error","ts":"2020-04-24T04:43:44.210Z","msg":"couldn't get cache from redis for account 1, reason: redisc: failed to get a connection"}
```
Main problem is for dev environments

**Comment by mna** [comment]
Hello Nikita,

Redis cluster requires at least 3 master nodes to work as expected:

> Note that the minimal cluster that works as expected requires to contain at least three master nodes. For your first tests it is strongly suggested to start a six nodes cluster with three masters and three slaves.
(https://redis.io/topics/cluster-tutorial)

The problem with a single node running in cluster mode is that the `CLUSTER SLOTS` command that redisc uses to detect the topology returns an empty set, so there is absolutely no information as to what node address handles what key, and `CUSTER INFO` goes a step further, it returns:

```
cluster_state:fail
cluster_slots_assigned:0
```

Even if I wanted to allow a special mode where it's ok to have a single node, redis will just refuse to serve anything that touches keys:

```
127.0.0.1:6379> set x a
(error) CLUSTERDOWN Hash slot not served
127.0.0.1:6379> get x
(error) CLUSTERDOWN Hash slot not served
```

So there's not much that can be done. It's relatively easy to spin up a redis cluster with a bash script, though, if you want to go that way.

Hope this helps,
Martin

**Comment by lohmag** [comment]
Actually it could be easily fixed like that -
`redis-cli CLUSTER ADDSLOTS $(for i in {0..16383}; do echo $i; done | xargs echo)`
Redis starts working in cluster mode only with one node.

**Comment by mna** [comment]
👍 cool, even better.

**Comment by lohmag** [comment]
I think you didn't understand me. CLUSTER ADDSLOTS is a necessary command to create cluster, so you can create a cluster from one redis master node. Without it redis will work in standalone mode.

**Comment by mna** [comment]
Yeah, I thought you meant that the reason your standalone mode did not work was because you did not run this command? Did you try starting the standalone redis server and running that CLUSTER ADDSLOTS command? It does work for me, i.e. this program returns the value of the key correctly:

```
func main() {
	// create the cluster
	cluster := redisc.Cluster{
		StartupNodes: []string{":6379"},
		DialOptions:  []redis.DialOption{redis.DialConnectTimeout(5 * time.Second)},
		CreatePool:   createPool,
	}
	defer cluster.Close()

	// initialize its mapping
	if err := cluster.Refresh(); err != nil {
		log.Fatalf("Refresh failed: %v", err)
	}

	// grab a connection from the pool
	conn := cluster.Get()
	defer conn.Close()

	// call commands on it
	s, err := redis.String(conn.Do("GET", "some-key"))
	if err != nil {
		log.Fatalf("GET failed: %v", err)
	}
	log.Println(s)
}
```

I start the single redis-server instance with this config:

```
port 6379
cluster-enabled yes
cluster-config-file nodes.0.out
cluster-node-timeout 5000
appendonly no
```

And I run the `CLUSTER ADDSLOTS` command exactly as you mentioned. If that doesn't work for you there may be some specific command you're using that maybe fails in that scenario, or you're having unrelated connection problems, you'll have to give me more details with reproducible and runnable code.
