### ISSUE TITLE
Separate pool for masters and slaves?

### ISSUE THREAD

**Issue by JulieVogelman** [mna/redisc#34]
Helm’s redis and redis-cluster charts seem to create one Kubernetes service for hitting the master(s) and one Kubernetes service for hitting the slave(s). I would like to direct my readonly queries to the slaves and my write queries to the masters.

I’d like to use a redisc Cluster with an underlying Pool. Since I have two different endpoints - one for masters and one for slaves - it seems I need to create two different Clusters, each with their own Pool. Is this correct?

**Comment by JulieVogelman** [comment]
I guess the Helm chart also deploys a headless service - should I be using that instead of the master and slave services perhaps to get to the underlying nodes?

**Comment by JulieVogelman** [comment]
Okay, I just found this other issue which is very similar to mine and has helped explain things: https://github.com/mna/redisc/issues/13

So, maybe I can use a single Cluster with StartupNodes perhaps equal to my master service and slave service endpoints?

**Comment by mna** [comment]
Hello,

I'm not familiar with helm but yes for a given Redis cluster, you should use a single `redisc.Cluster` with some known valid startup node addresses, and it will automatically detect the cluster. The underlying pools are managed automatically, one pool is created for each node. To direct your read-only queries to replica nodes, you call `conn.ReadOnly()` before running commands with that connection (see https://godoc.org/github.com/mna/redisc#Conn.ReadOnly).

Hope this helps,
Martin

**Comment by JulieVogelman** [comment]
Thanks, Martin. I will try using the master service and the slave service as my StartupNodes and see how that goes. As for calling conn.ReadOnly(), I figure I will call that each time I want to use a connection from the Pool and send it a read query? (as opposed to having connections that are permanently designated as read-only connections)

**Comment by mna** [comment]
Yes, basically you do:

```
conn := cluster.Get()
defer conn.Close()
// using redisc.ReadOnlyConn is easier than calling conn.ReadOnly() because 
// the connection returned by cluster.Get()
// is of type redis.Conn, you'd have to convert it to *redisc.Conn otherwise.
if err := redisc.ReadOnlyConn(conn); err != nil {
    // handle error...
}
// use the conn for readonly queries, e.g.:
s, err := redis.String(conn.Do("GET", "some-key"))
if err != nil {
    // handle error...
}
```

**Comment by JulieVogelman** [comment]
Thanks very much. I'll close this.

**Comment by JulieVogelman** [comment]
Sorry, reopening with a question. Should I still call Cluster.Refresh() if I don't have multiple shards but just have a master node with slave nodes?

**Comment by mna** [comment]
If you don't have a redis cluster, you shouldn't use this package, it will only add overhead. If you do have a cluster, you should call Refresh before you start getting connections from the `Cluster` (typically at startup in your main), in order to avoid paying the cost of the cluster discovery on first use.

In the future please open new issues when you have different questions instead of reopening an unrelated one.

Martin

**Comment by JulieVogelman** [comment]
Will do. Thank you.
