### ISSUE TITLE
Pls Help

### ISSUE THREAD

**Issue by Superboss12309** [mna/redisc#41]
Issue Downloading
![Screenshot (184)](https://user-images.githubusercontent.com/111625044/185731024-d390f1dc-0392-41d8-b426-934d6f020aba.jpg)

**Comment by mna** [comment]
Hello,

Looks like you're installing some python project that has a dependency on a `redisc` python module, this has nothing to do with this `redisc` which is a Go package, sorry. I took a quick look in pypi but couldn't find anything called redisc in python world (which might be the issue - maybe your python project has a typo in a dependency name). I'd suggest reaching out to the maintainer of the python project you're trying to install.

Martin
