### ISSUE TITLE
Does it support redis module command?

### ISSUE THREAD

**Issue by githubname1024** [mna/redisc#49]
I want to exec redis module command in redis cluster. Does this cluster client support redis module command, for example redisearch?
Thank you very much.

**Comment by mna** [comment]
Hello,

Yes, you can use any command from redis or any module/extension. `redisc` is only concerned with handling the redis cluster specifics, the connections you get from `redisc` are ultimately `redigo` connections (https://pkg.go.dev/github.com/gomodule/redigo/redis), so whatever you can do with redigo (that are valid commands in cluster mode), you can do with `redisc`.

Have fun!
Martin

**Comment by githubname1024** [comment]
OK，I got it. Thank you very much.
