### ISSUE TITLE
redisc.closed error

### ISSUE THREAD

**Issue by shreekeshav** [mna/redisc#6]
Hi ,
When I run the follow code I get a redisc.Connection closed error. Working on an Amazon cluster with 9 nodes(3 masters and each master has two slaves.) .Error I get is SET failed: redisc: closed.
 It works when I comment out the defer cluster.Close and defer Conn.close()
`

    package main
    import (
    "github.com/garyburd/redigo/redis"
     "github.com/mna/redisc"
     "github.com/davecgh/go-spew/spew"
     "log"
    "time"
    )

    var (
	pool    *redis.Pool
    )
    func createPool(addr string, opts ...redis.DialOption) (*redis.Pool, error) {
 
	     return &redis.Pool{
		MaxIdle:     5,
		MaxActive:   10,
		IdleTimeout: time.Minute,
		Dial: func() (redis.Conn, error) {
                log.Println(addr)
			c, err := redis.Dial("tcp", addr, opts...)
                        if err != nil {
				log.Panic(err)
			}
			return c, err
		},
		TestOnBorrow: func(c redis.Conn, t time.Time) error {
			_, err := c.Do("PING")
			return err
		},
	}, nil
    
    }
    func redisConnection() redis.Conn {  
      cluster := redisc.Cluster{
                    StartupNodes: []string{"*****.clustercfg.usw2.cache.amazonaws.com:6379"},
		    DialOptions:  []redis.DialOption{redis.DialConnectTimeout(5 * time.Minute)},
                    CreatePool:createPool,  
        }
       defer cluster.Close()
       if err := cluster.Refresh(); err != nil {
		log.Fatalf("Refresh failed: %v", err)
        }else{
            log.Println("Refresh worked")
        }
	conn := cluster.Get()
        defer conn.Close()
    
    if(conn != nil){
        rc, err := redisc.RetryConn(conn, 9, 100*time.Millisecond)
        if(err == nil){
            return rc
        }else{
            spew.Dump(err)
            return nil
        }
     }else{
        log.Println("Conn is nil")
        return nil   
        }
	return nil
    }
    func main() {
        rcon := redisConnection()
        defer rcon.Close()
        _,err1 := rcon.Do("SET", "mykey", "23")
	if err1 != nil {
		log.Fatalf("SET failed: %v", err1)
	}
        v, err := rcon.Do("GET", "mykey")
	if err != nil {
		log.Fatalf("GET failed: %v", err)
        }else{
            log.Println("My val",v)
      }
    }

`

**Comment by mna** [comment]
Hello,

This is a misuse of the `defer` statement. Defer executes the function when the surrounding function returns, so what you're doing here is closing the connection and the cluster when `redisConnection` returns, so when you use the connection in `main`, it is already closed. See https://golang.org/ref/spec#Defer_statements for details. Also, `RetryConn` wraps an existing connection, it doesn't create a new one, so you must not close the wrapped connection before returning.

The `Cluster` type is designed to be long-lived, like a redigo Pool, you don't want to create it each time a connection is needed. E.g. in this example it should be created and refreshed in main, before requesting connections.

Hope this helps,
Martin

P.S. you should `gofmt` your code before sharing, it makes it that much easier to read: https://blog.golang.org/go-fmt-your-code

**Comment by shreekeshav** [comment]
Thank you for ur help. When I do not close the cluster or the connections (also moved the creation in to main) I get a connection time out error.

    func main() {
	cluster := redisc.Cluster{
		StartupNodes: []string{"***amzaws.com:6379"},
		DialOptions:  []redis.DialOption{redis.DialConnectTimeout(5 * time.Second)},
		CreatePool:   createPool,
	}
	if err := cluster.Refresh(); err != nil {
		log.Fatalf("Refresh failed: %v", err)
	} else {
		log.Println("Refresh worked")
	}
	conn := cluster.Get()

	rc, err := redisc.RetryConn(conn, 9, 100*time.Millisecond)
	defer rc.Close()
	_, err1 := rc.Do("SET", "mykey", "23")
	if err1 != nil {
		log.Fatalf("SET failed: %v", err1)
	} else {
		log.Println("Set succeeded")
	}
	v, err := rc.Do("GET", "mykey")
	if err != nil {
		log.Fatalf("GET failed: %v", err)
	} else {
		log.Println("My val", v)
	}

    }

`

**Comment by mna** [comment]
I can't help you with that, you can try using a longer timeout and troubleshooting your redis instances' conection (connect via redis-cli, check the aws console, etc.).

**Comment by shreekeshav** [comment]
I could resolve the connection issues  but have some issues with HGET ALL and SCAN . Will post a separate issue for that.
